# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

newDd <- function() {
    .Call(`_odrr6_newDd`)
}

newDdLong <- function(l) {
    .Call(`_odrr6_newDdLong`, l)
}

getDays <- function(p) {
    .Call(`_odrr6_getDays`, p)
}

newDt <- function() {
    .Call(`_odrr6_newDt`)
}

newDtSexp <- function(s) {
    .Call(`_odrr6_newDtSexp`, s)
}

newDtYMD <- function(y, m, d) {
    .Call(`_odrr6_newDtYMD`, y, m, d)
}

newDtGregDate <- function(d) {
    .Call(`_odrr6_newDtGregDate`, d)
}

getIMMDate <- function(mon, year) {
    .Call(`_odrr6_getIMMDate`, mon, year)
}

getNthDayOfWeek <- function(nthday, dow, mon, year) {
    .Call(`_odrr6_getNthDayOfWeek`, nthday, dow, mon, year)
}

getLastDayOfWeekInMonth <- function(weekday, mon, year) {
    .Call(`_odrr6_getLastDayOfWeekInMonth`, weekday, mon, year)
}

getFirstDayOfWeekInMonth <- function(weekday, mon, year) {
    .Call(`_odrr6_getFirstDayOfWeekInMonth`, weekday, mon, year)
}

getFirstDayOfWeekAfter <- function(weekday, date) {
    .Call(`_odrr6_getFirstDayOfWeekAfter`, weekday, date)
}

getLastDayOfWeekBefore <- function(weekday, date) {
    .Call(`_odrr6_getLastDayOfWeekBefore`, weekday, date)
}

setFromLocalClock <- function(p) {
    .Call(`_odrr6_setFromLocalClock`, p)
}

setFromUTCClock <- function(p) {
    .Call(`_odrr6_setFromUTCClock`, p)
}

getLocalDay <- function(p) {
    .Call(`_odrr6_getLocalDay`, p)
}

getUTCDay <- function(p) {
    .Call(`_odrr6_getUTCDay`, p)
}

getYear <- function(p) {
    .Call(`_odrr6_getYear`, p)
}

getMonth <- function(p) {
    .Call(`_odrr6_getMonth`, p)
}

getDay <- function(p) {
    .Call(`_odrr6_getDay`, p)
}

getDayOfWeek <- function(p) {
    .Call(`_odrr6_getDayOfWeek`, p)
}

setDate <- function(p, dt) {
    .Call(`_odrr6_setDate`, p, dt)
}

getDate <- function(p) {
    .Call(`_odrr6_getDate`, p)
}

getWeekNumber <- function(p) {
    .Call(`_odrr6_getWeekNumber`, p)
}

getJulianDay <- function(p) {
    .Call(`_odrr6_getJulianDay`, p)
}

getModJulianDay <- function(p) {
    .Call(`_odrr6_getModJulianDay`, p)
}

setEndOfMonth <- function(p) {
    .Call(`_odrr6_setEndOfMonth`, p)
}

getEndOfMonth <- function(p) {
    .Call(`_odrr6_getEndOfMonth`, p)
}

setFirstOfNextMonth <- function(p) {
    .Call(`_odrr6_setFirstOfNextMonth`, p)
}

getFirstOfNextMonth <- function(p) {
    .Call(`_odrr6_getFirstOfNextMonth`, p)
}

setEndOfBizWeek <- function(p) {
    .Call(`_odrr6_setEndOfBizWeek`, p)
}

addDays <- function(p, len) {
    .Call(`_odrr6_addDays`, p, len)
}

subtractDays <- function(p, len) {
    .Call(`_odrr6_subtractDays`, p, len)
}

addMonths <- function(p, m) {
    .Call(`_odrr6_addMonths`, p, m)
}

addYears <- function(p, y) {
    .Call(`_odrr6_addYears`, p, y)
}

setIMMDate <- function(p, mon, year) {
    .Call(`_odrr6_setIMMDate`, p, mon, year)
}

showDate <- function(p) {
    invisible(.Call(`_odrr6_showDate`, p))
}

newPt <- function() {
    .Call(`_odrr6_newPt`)
}

newPtSexp <- function(s) {
    .Call(`_odrr6_newPtSexp`, s)
}

newPtValue <- function(yy, mm, dd, hh, min, sec, fracsecs) {
    .Call(`_odrr6_newPtValue`, yy, mm, dd, hh, min, sec, fracsecs)
}

setFromLocalTimeInSeconds <- function(p) {
    .Call(`_odrr6_setFromLocalTimeInSeconds`, p)
}

setFromUTCInSeconds <- function(p) {
    .Call(`_odrr6_setFromUTCInSeconds`, p)
}

setFromLocalTimeInMicroSeconds <- function(p) {
    .Call(`_odrr6_setFromLocalTimeInMicroSeconds`, p)
}

setFromUTCInMicroSeconds <- function(p) {
    .Call(`_odrr6_setFromUTCInMicroSeconds`, p)
}

setFromDatetime <- function(p, s) {
    .Call(`_odrr6_setFromDatetime`, p, s)
}

setFromDouble <- function(p, d) {
    .Call(`_odrr6_setFromDouble`, p, d)
}

getDatetimePt <- function(p) {
    .Call(`_odrr6_getDatetimePt`, p)
}

getDatePt <- function(p) {
    .Call(`_odrr6_getDatePt`, p)
}

addHours <- function(p, h) {
    .Call(`_odrr6_addHours`, p, h)
}

addMinutes <- function(p, m) {
    .Call(`_odrr6_addMinutes`, p, m)
}

addSeconds <- function(p, s) {
    .Call(`_odrr6_addSeconds`, p, s)
}

addFractionalSeconds <- function(p, s) {
    .Call(`_odrr6_addFractionalSeconds`, p, s)
}

